application: pyconindia2014

version: 1

runtime: python27
api_version: 1

threadsafe: true

default_expiration: "30d"

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2 
  version: latest

- name: markupsafe 
  version: latest

handlers:

- url: /.*
  script: main.app
skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*sh
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.template$
- tmp
- tests
